apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: quarkus-alert
  namespace: quarkus
spec:
  groups:
  - name: quarkus-example
    rules:
    - alert: VersionAlert
      expr: version{job="quarkus-quickstart"} == 0
